
version: "3.3"

services:
  db:
    container_name: metrocensus-db
    image: postgres:12.2
    ports:
      - "5435:5433"
    volumes:
      - postgres_volume:/var/lib/postgresql
    env_file:
      - metrocensus/.env
  api: &api
    container_name: metrocensus-panel-api
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    command: gunicorn metrocensus.metrocensus.wsgi:application -w 2 -b :8088 --reload
    ports:
      - "8088:8008"
    volumes:
      - .:/app
      - ./tests:/app/tests
      - ./data/media:/public/media
    depends_on:
      - db
      - rabbitmq
      - celery_worker
    env_file:
      - metrocensus/.env
    stdin_open: true
    tty: true

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-alpine

  celery_worker:
    <<: *api
    build:
      context: .
    container_name: celery_worker
    restart: "no"
    command: "celery -A metrocensus.metrocensus worker --loglevel=info"
    ports: []
    environment:
      - COLUMNS=80
    depends_on:
      - rabbitmq
      - db

  celery-beat:
    build:
      context: .
    volumes:
      - ./metrocensus:/app/metrocensus
      - ./tests:/app/tests
      - ./data/media:/public/media
    container_name: celery_beat
    command: "celery -A metrocensus.metrocensus worker --loglevel=info"
    depends_on:
      - rabbitmq
      - db

volumes:
  postgres_volume:
