
version: "3.3"

services:
  db:
    container_name: metrocensus-db
    image: postgres:12.2
    ports:
      - "5435:5433"
    volumes:
      - postgres_volume:/var/lib/postgresql
    env_file:
      - metrocensus/.env

  metrocensus-api: &metrocensus
    container_name: metrocensus-panel-api
    build:
      context: ./metrocensus
      dockerfile: Dockerfile
    restart: unless-stopped
    command: bash -c " python manage.py runserver 0.0.0.0:8002"
    ports:
      - "8002:8002"
    volumes:
      - ./metrocensus:/app
      - .metrocensus/tests:/app/tests
      - ./metrocensus/data/media:/public/media
    depends_on:
      - db
      - rabbitmq
      - celery_worker
    env_file:
      - metrocensus/.env
    stdin_open: true
    tty: true
  

  bank-api: &bank
    container_name: bank-api
    build:
      context: ./bank
      dockerfile: Dockerfile
    restart: unless-stopped
    command: bash -c "python manage.py runserver 0.0.0.0:8001"
    #expose:
    # - 9088
    ports:
      - "8001:8001"
    volumes:
      - ./bank:/app
      - ./bank/tests:/app/tests
      - ./bank/data/media:/public/media
    depends_on:
      - db
      - rabbitmq
      - celery_worker
    env_file:
      - bank/.env
    stdin_open: true
    tty: true

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.7-alpine

  celery_worker:
    <<: *bank
    build:
      context: ./bank
    volumes:
      - ./bank:/app
    container_name: celery_worker
    restart: "no"
    command: "celery -A bank worker --loglevel=info"
    ports: []
    environment:
      - COLUMNS=80
    depends_on:
      - rabbitmq
      - db

  celery-beat:
    build:
      context: ./bank
    container_name: celery_beat
    volumes:
      - ./bank:/app
    command: "celery -A bank beat --loglevel=info"
    depends_on:
      - rabbitmq

volumes:
  postgres_volume:
