
version: "3.3"

services:
  db:
    container_name: metrocensus-db
    image: postgres:12.2
    ports:
      - "5435:5433"
    volumes:
      - postgres_volume:/var/lib/postgresql
    env_file:
      - metrocensus/.env
  api:
    container_name: metrocensus-panel-api
    build:
      context: .
      dockerfile: Dockerfile
    command: bash -c "sleep 2s && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8081:8001"
    volumes:
      - ./metrocensus:/app/metrocensus
      - ./tests:/app/tests
      - ./data/media:/public/media
    depends_on:
      - db
    env_file:
      - metrocensus/.env
    stdin_open: true
    tty: true
volumes:
  postgres_volume: